#!/usr/bin/env python3
"""Build a leakage-free, survey-level YOLO dataset from the MILCO/NOMBO archive.

Why survey-level (year-level) splits?
------------------------------------
Side-scan frames from one survey are highly correlated: the same seabed, the
same sonar gain settings, often the SAME physical object across consecutive
pings. A random image split therefore leaks test information into training and
inflates every metric. We split by acquisition YEAR, which in this dataset
corresponds to distinct survey campaigns/hardware settings. Numbers produced
this way are lower but honest, and they measure what actually matters:
generalisation to an unseen survey.

Source: Pessanha Santos, N. & Moura, R. (2024), "Side-scan sonar imaging data of
underwater vehicles for mine detection", Data in Brief. CC BY 4.0.
figshare DOI: 10.6084/m9.figshare.24574879
"""

from __future__ import annotations

import argparse
import json
import shutil
from collections import Counter
from pathlib import Path

# Survey-year assignment.
#   train: 2015 carries most annotated targets; 2010 contributes a large pool of
#          pure natural-seabed frames (hard negatives).
#   val  : 2017, an unseen survey used only for threshold/calibration fitting.
#   test : 2018 + 2021, fully held-out surveys. 2018 in particular is dominated
#          by negative frames, which is what makes it a real false-positive test.
SPLIT_BY_YEAR = {
    "train": ["2015", "2010"],
    "val": ["2017"],
    "test": ["2018", "2021"],
}

CLASS_NAMES = ["MILCO", "NOMBO"]


def find_year_dir(root: Path, year: str) -> Path:
    for cand in (root / f"{year}_x" / year, root / year, root / f"{year}_x"):
        if cand.is_dir() and any(cand.glob("*.jpg")):
            return cand
    raise FileNotFoundError(f"could not locate image directory for year {year} under {root}")


def stats_for(label_files: list[Path]) -> dict:
    counts: Counter = Counter()
    empty = 0
    for lf in label_files:
        rows = [r for r in lf.read_text().splitlines() if r.strip()]
        if not rows:
            empty += 1
        for r in rows:
            counts[CLASS_NAMES[int(r.split()[0])]] += 1
    return {
        "frames": len(label_files),
        "negative_frames": empty,
        "positive_frames": len(label_files) - empty,
        "objects": dict(counts),
        "total_objects": sum(counts.values()),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", default="data/raw/milco_nombo")
    ap.add_argument("--out", default="data/processed/milco_nombo_yolo")
    ap.add_argument("--copy", action="store_true", help="copy files instead of symlinking")
    args = ap.parse_args()

    raw, out = Path(args.raw).resolve(), Path(args.out).resolve()
    if out.exists():
        shutil.rmtree(out)

    manifest: dict = {
        "dataset": "milco_nombo",
        "source_doi": "10.6084/m9.figshare.24574879",
        "license": "CC BY 4.0",
        "split_strategy": "survey-year level (no random image shuffling)",
        "split_by_year": SPLIT_BY_YEAR,
        "class_names": CLASS_NAMES,
        "splits": {},
    }

    for split, years in SPLIT_BY_YEAR.items():
        img_dir = out / split / "images"
        lbl_dir = out / split / "labels"
        img_dir.mkdir(parents=True, exist_ok=True)
        lbl_dir.mkdir(parents=True, exist_ok=True)

        placed_labels: list[Path] = []
        members: list[str] = []

        for year in years:
            ydir = find_year_dir(raw, year)
            for img in sorted(ydir.glob("*.jpg")):
                lbl = img.with_suffix(".txt")
                if not lbl.exists():
                    continue  # never fabricate an annotation
                di, dl = img_dir / img.name, lbl_dir / lbl.name
                if args.copy:
                    shutil.copy2(img, di)
                    shutil.copy2(lbl, dl)
                else:
                    di.symlink_to(img)
                    dl.symlink_to(lbl)
                placed_labels.append(lbl)
                members.append(f"{year}/{img.name}")

        st = stats_for(placed_labels)
        st["years"] = years
        st["members_sample"] = members[:3]
        manifest["splits"][split] = st
        print(f"{split:5s} years={years} frames={st['frames']:4d} "
              f"neg={st['negative_frames']:4d} objs={st['objects']}")

    # Ultralytics data yaml
    (out / "data.yaml").write_text(
        f"# Auto-generated by scripts/prepare_milco_nombo.py -- do not hand-edit\n"
        f"path: {out}\ntrain: train/images\nval: val/images\ntest: test/images\n"
        f"nc: {len(CLASS_NAMES)}\nnames:\n"
        + "".join(f"  {i}: {n}\n" for i, n in enumerate(CLASS_NAMES))
    )

    splits_dir = Path("data/splits")
    splits_dir.mkdir(parents=True, exist_ok=True)
    (splits_dir / "milco_nombo_survey_split.json").write_text(json.dumps(manifest, indent=2))

    # Full member lists, so a split is exactly reproducible / auditable.
    for split in SPLIT_BY_YEAR:
        names = sorted(p.name for p in (out / split / "images").iterdir())
        (splits_dir / f"milco_nombo_{split}.txt").write_text("\n".join(names) + "\n")

    print(f"\nwrote {out}/data.yaml")
    print(f"wrote {splits_dir}/milco_nombo_survey_split.json")


if __name__ == "__main__":
    main()
