#!/usr/bin/env python3
"""Build a speckle-AUGMENTED training set to address the documented weakness.

Phase 1 measured that detection collapses under added speckle (recall -> 0). The
fix for a distribution the detector never saw is to TRAIN on it, not to filter at
inference. This builder writes:

    train/  = every raw frame  PLUS  a multiplicative-speckle copy of it
    val/    = raw (unchanged)      -- selection/early-stopping on clean data
    test/   = raw (unchanged)      -- clean test stays comparable to E04

so the model sees both clean and speckled seabed during training while every
reported clean-test number remains directly comparable to the raw baseline. A
separate speckled test set is generated by scripts/robustness.py at eval time.

Speckle is multiplicative (gamma), the correct model for coherent sonar, matching
scripts/robustness.py so train-time and eval-time noise are the same family.
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import cv2
import numpy as np

# Deterministic per-image seed (Math.random-free equivalent): seed from index.
def speckle(img, sigma, rng):
    g = rng.gamma(shape=1.0 / max(sigma, 1e-3), scale=max(sigma, 1e-3), size=img.shape)
    return np.clip(img.astype(np.float32) * g, 0, 255).astype(np.uint8)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="data/processed/milco_nombo_yolo")
    ap.add_argument("--dst", default="data/processed/milco_nombo_yolo_speckle")
    ap.add_argument("--sigmas", default="0.25,0.5", help="speckle levels for the extra copies")
    args = ap.parse_args()
    src, dst = Path(args.src), Path(args.dst)
    if dst.exists():
        shutil.rmtree(dst)
    sigmas = [float(x) for x in args.sigmas.split(",")]

    for split in ("train", "val", "test"):
        (dst / split / "images").mkdir(parents=True, exist_ok=True)
        (dst / split / "labels").mkdir(parents=True, exist_ok=True)
        n_clean = n_spk = 0
        for i, ip in enumerate(sorted((src / split / "images").glob("*.jpg"))):
            g = cv2.imread(str(ip), cv2.IMREAD_GRAYSCALE)
            if g is None:
                continue
            lp = (src / split / "labels" / ip.name).with_suffix(".txt")
            # clean copy always
            cv2.imwrite(str(dst / split / "images" / ip.name), g, [cv2.IMWRITE_JPEG_QUALITY, 95])
            shutil.copy2(lp, dst / split / "labels" / lp.name)
            n_clean += 1
            # speckled copies for TRAIN only
            if split == "train":
                for j, sig in enumerate(sigmas):
                    rng = np.random.default_rng(1000 * i + j)   # deterministic
                    sp = speckle(g, sig, rng)
                    name = ip.stem + f"_spk{j}.jpg"
                    cv2.imwrite(str(dst / split / "images" / name), sp, [cv2.IMWRITE_JPEG_QUALITY, 95])
                    shutil.copy2(lp, (dst / split / "labels" / name).with_suffix(".txt"))
                    n_spk += 1
        print(f"  {split:5s} clean={n_clean:4d} speckled={n_spk:4d}")

    (dst / "data.yaml").write_text(
        f"# Speckle-augmented (train only). Generated by scripts/prepare_speckle_aug.py\n"
        f"path: {dst.resolve()}\ntrain: train/images\nval: val/images\ntest: test/images\n"
        f"nc: 2\nnames:\n  0: MILCO\n  1: NOMBO\n")
    # A model trained here still runs inference on RAW frames -> profile 'none'.
    (dst / "preprocess_config.json").write_text(
        '{"profile": "none", "note": "speckle augmentation is a TRAINING transform; '
        'inference is on raw frames, so the checkpoint profile is none.", '
        f'"speckle_sigmas": {sigmas}}}')
    print(f"\nwrote {dst}/data.yaml  (sigmas={sigmas})")


if __name__ == "__main__":
    main()
