#!/usr/bin/env python3
"""Materialise a PREPROCESSED copy of the dataset.

Why this exists
---------------
Applying sonar preprocessing only at inference, to a detector trained on raw
frames, shifts the input distribution and *degrades* performance -- we measured
exactly that (see docs/BENCHMARKS.md, "Train/inference consistency"). If a
preprocessing chain is worth having, the detector must be TRAINED on its output.

This script writes a parallel dataset with the chosen profile baked in, so that
"does preprocessing help?" can be answered by a matched comparison instead of a
mismatched one.

Labels are copied unchanged: every operation in the `standard` profile is
intensity-only and preserves geometry, so boxes remain valid. Profiles that
change geometry (`water_column_mode="split"`, slant-range correction) are
REFUSED here rather than silently invalidating the annotations.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

import cv2

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from aquashield.sonar.preprocess import PROFILES, PreprocessConfig, preprocess  # noqa: E402

GEOMETRY_CHANGING = "this profile alters image geometry, which would invalidate the labels"


def check_geometry_safe(cfg: PreprocessConfig) -> None:
    if cfg.water_column_removal and cfg.water_column_mode == "split":
        raise ValueError(f"water_column_mode='split': {GEOMETRY_CHANGING}")
    if cfg.slant_range_correction:
        raise ValueError(f"slant_range_correction: {GEOMETRY_CHANGING}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="data/processed/milco_nombo_yolo")
    ap.add_argument("--dst", default="data/processed/milco_nombo_yolo_pp")
    ap.add_argument("--profile", default="standard", choices=list(PROFILES))
    ap.add_argument("--water-column-removal", action="store_true")
    args = ap.parse_args()

    cfg = PROFILES[args.profile]
    if args.water_column_removal:
        cfg = PreprocessConfig(**{**cfg.as_dict(),
                                  "dr_clip_percentiles": tuple(cfg.dr_clip_percentiles),
                                  "water_column_removal": True,
                                  "water_column_mode": "inpaint"})
    check_geometry_safe(cfg)

    src, dst = Path(args.src), Path(args.dst)
    if dst.exists():
        shutil.rmtree(dst)

    counts = {}
    for split in ("train", "val", "test"):
        (dst / split / "images").mkdir(parents=True, exist_ok=True)
        (dst / split / "labels").mkdir(parents=True, exist_ok=True)
        n = 0
        for ip in sorted((src / split / "images").glob("*.jpg")):
            g = cv2.imread(str(ip), cv2.IMREAD_GRAYSCALE)
            if g is None:
                continue
            out = preprocess(g, cfg).image
            cv2.imwrite(str(dst / split / "images" / ip.name), out,
                        [cv2.IMWRITE_JPEG_QUALITY, 95])
            lp = (src / split / "labels" / ip.name).with_suffix(".txt")
            shutil.copy2(lp, dst / split / "labels" / lp.name)
            n += 1
        counts[split] = n
        print(f"  {split:5s} {n:4d} frames preprocessed")

    (dst / "data.yaml").write_text(
        f"# Auto-generated by scripts/prepare_preprocessed.py\n"
        f"# profile: {args.profile}  water_column_removal: {cfg.water_column_removal}\n"
        f"path: {dst.resolve()}\ntrain: train/images\nval: val/images\ntest: test/images\n"
        f"nc: 2\nnames:\n  0: MILCO\n  1: NOMBO\n")
    (dst / "preprocess_config.json").write_text(json.dumps({
        "source": str(src), "profile": args.profile, "config": cfg.as_dict(),
        "counts": counts,
        "note": "Labels copied unchanged; all applied operations are intensity-only "
                "and preserve geometry."}, indent=2))
    print(f"\nwrote {dst}/data.yaml")
    print(f"profile: {args.profile}  water_column_removal={cfg.water_column_removal}")


if __name__ == "__main__":
    main()
